Formatted code

diff --git a/gbin/checkDuplicate b/gbin/checkDuplicate
--- a/gbin/checkDuplicate
+++ b/gbin/checkDuplicate
@@ -8,15 +8,14 @@
 # Compare one with another in the given directory
 # If any Duplicate file Found, it will print it in the console
 
-
 while getopts "p:d:hs:r" opt; do
 	case "$opt" in
-		p) arg="${OPTARG}";;
-		d) depth="${OPTARG}";;
-		h) echo -e "USAGE --> \np - Path to scan \nd - Max Depth to scan in sub directories\ns - max file size that it compares (uses find command's like size +100k +1G)\nr - Remove the duplicate file without asking.." && exit 0;;
-		s) size=$OPTARG;;
-		r) remove="remove";;
-		*) echo "Invalid Option; -h for Help" && exit 1;;
+	p) arg="${OPTARG}" ;;
+	d) depth="${OPTARG}" ;;
+	h) echo -e "USAGE --> \np - Path to scan \nd - Max Depth to scan in sub directories\ns - max file size that it compares (uses find command's like size +100k +1G)\nr - Remove the duplicate file without asking.." && exit 0 ;;
+	s) size=$OPTARG ;;
+	r) remove="remove" ;;
+	*) echo "Invalid Option; -h for Help" && exit 1 ;;
 	esac
 done
 
@@ -25,26 +24,26 @@ green='\033[01;32m'
 yellow='\033[0;33m'
 off='\033[0m'
 
-[ -z "$arg" ] && arg="." || [ "$arg" != "." ] && [ ! -e "$arg" ] && echo "Given Directory not exists.. " && exit 2;
+[ -z "$arg" ] && arg="." || [ "$arg" != "." ] && [ ! -e "$arg" ] && echo "Given Directory not exists.. " && exit 2
 
 find_cmd="find \"$arg\""
 
 if [[ -n "$depth" ]]; then
-  if [[ "$depth" =~ ^[0-9]+$ ]]; then
-    find_cmd+=" -maxdepth $depth"
-  else
-    echo "Please provide valid Depth in Numbers."
-    exit 3
-  fi
+	if [[ "$depth" =~ ^[0-9]+$ ]]; then
+		find_cmd+=" -maxdepth $depth"
+	else
+		echo "Please provide valid Depth in Numbers."
+		exit 3
+	fi
 fi
 
 if [[ -n "$size" ]]; then
-  if [[ "$size" =~ ^([+-][0-9]{1,6}[bcwkMG])$ ]]; then
-    find_cmd+=" -size $size"
-  else
-    echo "Please provide valid Size Ex. +100k, +2048c, -10G"
-    exit 4
-  fi
+	if [[ "$size" =~ ^([+-][0-9]{1,6}[bcwkMG])$ ]]; then
+		find_cmd+=" -size $size"
+	else
+		echo "Please provide valid Size Ex. +100k, +2048c, -10G"
+		exit 4
+	fi
 fi
 
 find_cmd+=" -type f"
@@ -52,7 +51,7 @@ find_cmd+=" -type f"
 count=$(eval "$find_cmd" 2>/dev/null | head -n 1000 | wc -l)
 
 if [ "$count" == 1000 ]; then
-	echo "Too Many Files to Compare.. Exiting.." && exit 5;
+	echo "Too Many Files to Compare.. Exiting.." && exit 5
 fi
 
 # Iterate over files in the current directory
@@ -65,23 +64,22 @@ progress=0
 echo -e "${green}Total ${count} files... Directory --> $(realpath "$arg")${off}\n"
 
 for file1 in $(eval "$find_cmd" 2>/dev/null); do
-	progress=$((progress+1));
-	echo -en "\033[K${yellow}Scanning  $((progress*100/count))% --> $file1 ${off}\r"
+	progress=$((progress + 1))
+	echo -en "\033[K${yellow}Scanning  $((progress * 100 / count))% --> $file1 ${off}\r"
 	if [ "$file1" != "${arr[$file1]}" ]; then
 		for file2 in $(eval "$find_cmd" 2>/dev/null); do
 			if [ "$file1" != "$file2" ] && cmp -s "$file1" "$file2"; then
-				if [ "$remove" == "remove" ];then
-					i=$((i+1));
+				if [ "$remove" == "remove" ]; then
+					i=$((i + 1))
 					echo -en "\033[K"
-					select s in "$file1" "$file2" "Skip"
-					do
+					select s in "$file1" "$file2" "Skip"; do
 						if [ "$s" != "Skip" ]; then
 							rm "$s" && echo -e "${red}Removed $s${off}" || echo "Error While Deleting $s"
 						fi
-					break
+						break
 					done
-				elif [ "$(wc -l < "$file1")" != 0 ]; then
-					i=$((i+1));
+				elif [ "$(wc -l <"$file1")" != 0 ]; then
+					i=$((i + 1))
 					echo "Duplicate --> $file1 --> $file2"
 				fi
 				arr["$file2"]="$file2"
@@ -96,4 +94,4 @@ read -n 1 -s -r -p "Press any key to continue"
 
 echo
 
-exit 0;
+exit 0
diff --git a/gbin/unins b/gbin/unins
--- a/gbin/unins
+++ b/gbin/unins
@@ -1,29 +1,29 @@
 #!/bin/bash
 
-arg=$1
+arg="$1"
 
-[ ! -n "$arg" ] && echo "Please provide the package name to uninstall" && exit 1;
+[ -z "$arg" ] && echo "Please provide the package name to uninstall" && exit 1
 
-[ ! -n "$(which $arg)" ] && echo "Package not found on the system.." && exit 1;
+[ -z "$(which "$arg")" ] && echo "Package not found on the system.." && exit 1
 
-uninstall(){
-	sudo apt remove -y $arg;
-	sudo apt autoremove;
-	sudo apt clean;
-	exit 0;
-}
-
-uninstall_all(){
-	sudo apt  purge -y $arg;
-	sudo apt autoremove;
+uninstall() {
+	sudo apt remove -y "$arg"
+	sudo apt autoremove
 	sudo apt clean
-	exit 0;
+	exit 0
 }
 
-echo -n "Do you want to completely remove with configuration files? (y/n)";
+uninstall_all() {
+	sudo apt purge -y "$arg"
+	sudo apt autoremove
+	sudo apt clean
+	exit 0
+}
 
-read conf;
+echo -n "Do you want to completely remove with configuration files? (y/n)"
 
-[ "$conf" = "Y" -o "$conf" = "y" -o "$conf" = "Yes" -o "$conf" = "yes" ] && uninstall_all;
+read conf
 
-[ "$conf" = "N" -o "$conf" = "n" -o "$conf" = "No" -o "$conf" = "no" ] && uninstall;
+[ "$conf" = "Y" -o "$conf" = "y" -o "$conf" = "Yes" -o "$conf" = "yes" ] && uninstall_all
+
+[ "$conf" = "N" -o "$conf" = "n" -o "$conf" = "No" -o "$conf" = "no" ] && uninstall
diff --git a/mybin/move_movie b/mybin/move_movie
--- a/mybin/move_movie
+++ b/mybin/move_movie
@@ -1,84 +1,89 @@
 #!/bin/bash
 
+# Author: Srithar
+# Created: 13th June 2023
+# Last Modified: 25th November 2023
+
+# Description:
+# Move the movie files into Specified Directory
+# It supports MKV/MP4 Files.
+
 moviefolder="/mnt/Data/Movies"
 
 if [ -z "$1" ] || { [[ "$1" != *.mkv ]] && [[ "$1" != *.mp4 ]]; }; then
- echo "Please input the movie mkv/mp4 file";
- echo "For MKV file, you can give subtitle in the second argument"
- echo "USAGE : $0 <moviepath> Subtitle to MUX"
- exit 1;
+	echo "Please input the movie mkv/mp4 file"
+	echo "For MKV file, you can give subtitle in the second argument"
+	echo "USAGE : $0 <moviepath> Subtitle to MUX"
+	exit 1
 fi
 
 if [[ ! -e "$1" ]]; then
- echo "File not found"
- exit 1;
+	echo "File not found"
+	exit 1
 fi
 
-TRIM(){
-echo "$1" | sed -e 's/^[ ]*//g' -e 's/[ ]*$//g'
+TRIM() {
+	echo "$1" | sed -e 's/^[ ]*//g' -e 's/[ ]*$//g'
 }
 
-DOPROPEDIT(){
+DOPROPEDIT() {
 
-mkvpropedit "${movie}" --edit info --set "title=${movie%.*}" >/dev/null
-echo "Title Updated";
+	mkvpropedit "${movie}" --edit info --set "title=${movie%.*}" >/dev/null
+	echo "Title Updated"
 
-num_attachments=$(mkvinfo "$movie" | grep "Track number" | tail -n 1 | grep -Eo 'Track number: [0-9]*'| grep -o '[0-9]*')
+	num_attachments=$(mkvinfo "$movie" | grep "Track number" | tail -n 1 | grep -Eo 'Track number: [0-9]*' | grep -o '[0-9]*')
 
-echo "Attchments Total : $num_attachments"
+	echo "Attchments Total : $num_attachments"
 
-if [[ -n num_attachments ]]; then
+	if [[ -n $num_attachments ]]; then
 
-for ((i=1; i<=$num_attachments; i++)); do
-    mkvpropedit "$movie" --edit track:$i --set "name="SritharBoss"" >/dev/null
-	echo "Attachment $i Updated"
-done
+		for ((i = 1; i <= num_attachments; i++)); do
+			mkvpropedit "$movie" --edit track:$i --set "name="SritharBoss"" >/dev/null
+			echo "Attachment $i Updated"
+		done
 
-fi
-
-}
-
-DOSUBMUX(){
- #movie="$(basename "$(echo $1)")"
- #movie_edit=$(echo "$movie" | sed 's/\([ -]*[([][a-zA-Z0-9]*.[a-zA-Z]\{2,6\}[])][ -]*\)//g')
-
- sub="$(basename "$(echo $2)")"
- sub_edit=$(echo "$sub" | sed 's/\([ -]*[([][a-zA-Z0-9]*.[a-zA-Z]\{2,6\}[])][ -]*\)//g')
-
- movie_ex_r=${movie_edit%.*}_SUB.mkv
-
- cd "$(dirname "$1")"
-
- [[ "$movie" != "$movie_edit" ]] && mv "$movie" "$movie_edit"
- [[ "$sub" != "$sub_edit" ]] && mv "$sub" "$sub_edit"
-
- mkvmerge -o "$movie_ex_r" "$movie_edit" --sub-charset 0:utf-8 --default-track 0:yes --track-name 0:"$sub_edit" && rm "$movie_edit" && rm "$sub_edit" && mv "$movie_ex_r" "$movie_edit"
+	fi
 
 }
 
+DOSUBMUX() {
+	#movie="$(basename "$(echo $1)")"
+	#movie_edit=$(echo "$movie" | sed 's/\([ -]*[([][a-zA-Z0-9]*.[a-zA-Z]\{2,6\}[])][ -]*\)//g')
 
-select lang in Tamil English Others/Malayalam Others/Telugu Others/Korean Others/Japanese Others/French Others/Spanish;
-do
-	moviefolder=$moviefolder
-    movie="$(basename "$(echo $1)")"
-    pattern="^([a-zA-Z0-9 -:]*)\s*\(([0-9]{4})\)"
-	cd "$(dirname "$1")"
+	sub="$(basename "$2")"
+	sub_edit=$(echo "$sub" | sed 's/\([ -]*[([][a-zA-Z0-9]*.[a-zA-Z]\{2,6\}[])][ -]*\)//g')
+
+	movie_ex_r=${movie_edit%.*}_SUB.mkv
+
+	cd "$(dirname "$1")" || exit
+
+	[[ "$movie" != "$movie_edit" ]] && mv "$movie" "$movie_edit"
+	[[ "$sub" != "$sub_edit" ]] && mv "$sub" "$sub_edit"
+
+	mkvmerge -o "$movie_ex_r" "$movie_edit" --sub-charset 0:utf-8 --default-track 0:yes --track-name 0:"$sub_edit" && rm "$movie_edit" && rm "$sub_edit" && mv "$movie_ex_r" "$movie_edit"
+
+}
+
+select lang in Tamil English Others/Malayalam Others/Telugu Others/Korean Others/Japanese Others/French Others/Spanish; do
+	movie="$(basename "$1")"
+	pattern="^([a-zA-Z0-9 -:]*)\s*\(([0-9]{4})\)"
+	cd "$(dirname "$1")" || exit
 	movie_edit=$(echo "$movie" | sed 's/\([ -]*[([][a-zA-Z0-9]*.[a-zA-Z]\{2,6\}[])][ -]*\)//g')
-	[[ -n $2 ]] && [[ "$1" == *.mkv ]] && DOSUBMUX "$1" "$2" && exit 0;
+	[[ -n $2 ]] && [[ "$1" == *.mkv ]] && DOSUBMUX "$1" "$2" && exit 0
 	[[ "$1" == *.mkv ]] && DOPROPEDIT
-	
-	if [[ $movie =~ $pattern ]];then
+
+	if [[ $movie =~ $pattern ]]; then
 		moviename=$(TRIM "${BASH_REMATCH[1]}")
 		year="${BASH_REMATCH[2]}"
 		moviefolder="$moviefolder/$lang/$moviename ($year)"
-		[[ ! -d "$moviefolder"  ]] && mkdir "$moviefolder"
-		[[ -e "$moviefolder/$movie" ]] && echo 'File Already Exists' && exit 1;
+		[[ ! -d "$moviefolder" ]] && mkdir "$moviefolder"
+		[[ -e "$moviefolder/$movie" ]] && echo 'File Already Exists' && exit 1
 		mv "$1" "$moviefolder"
 		echo File Moved
-		[[ "$moviefolder/$movie" != "$moviefolder/$movie_edit" ]]  && mv "$moviefolder/$movie" "$moviefolder/$movie_edit"
+		[[ "$moviefolder/$movie" != "$moviefolder/$movie_edit" ]] && mv "$moviefolder/$movie" "$moviefolder/$movie_edit"
 	else
 		echo "Filename is not in the pattern."
-    fi
-break
+	fi
+	break
 done
-exit 0;
+exit 0
