Logging issue fixed and formatted

diff --git a/mybin/sync_git b/mybin/sync_git
--- a/mybin/sync_git
+++ b/mybin/sync_git
@@ -2,7 +2,7 @@
 
 # Author: Srithar
 # Created: 18th July 2023
-# Last Modified: 18th July 2023
+# Last Modified: 25th November 2023
 
 # Description:
 # Syncs the list of folders provided with github
@@ -12,28 +12,27 @@ file="/mnt/Data/gitpath"
 
 [[ -f "$1" ]] && file="$1"
 
-echo -n "$(date "+%m-%d-%Y %H:%M --- ")" >> /home/srithar/log/cron_status.txt 2>&1
+echo -n "$(date "+%m-%d-%Y %H:%M --- [Git Sync] ")" >>/home/srithar/log/cron_status.txt 2>&1
 
 export DISPLAY=:0
 export XDG_RUNTIME_DIR=/run/user/$(id -u)
 
-cat "$file" | while read line 
-do
-	cd $line;
+while read line; do
+	cd "$line" || exit
 	echo "Processing --> $line"
-	
+
 	if [[ $(git pull) ]]; then
-		if [[ $(git status -s | wc -l) > 0 ]]; then
+		if [[ $(git status -s | wc -l) -gt 0 ]]; then
 			if [[ "$line" == '/mnt/Data/Docs' ]]; then
-				notify-send -i "$HOME/.icons/tick.svg" "Auto Committed : $line" "$(git status -s)";
-				git add . && git commit -m 'Auto Commit from crontab' && git push;
+				notify-send -i "$HOME/.icons/tick.svg" "Auto Committed : $line" "$(git status -s)"
+				git add . && git commit -m 'Auto Commit from crontab' && git push
 			else
-				notify-send -i "$HOME/.icons/warning.png" "Sync Pending $line" "$(git status -s)";
+				notify-send -i "$HOME/.icons/warning.png" "Sync Pending $line" "$(git status -s)"
 			fi
 		fi
 	else
-		echo "Error while pulling" >> /home/srithar/log/cron_status.txt; exit 1
+		echo "Error while pulling. Possibly, Internet Down" >>/home/srithar/log/cron_status.txt && exit 1
 	fi
-done
+done <"$file"
 
-echo "Git Sync Done.." >> /home/srithar/log/cron_status.txt
+echo "Git Sync Done.." >>/home/srithar/log/cron_status.txt
